spring:
  application:
    name: SyncStoreManagement
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Sofia
        format_sql: 'TRUE'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type.descriptor: WARN
      nodeValue: WARN
    root: INFO
    blog: WARN
    runtime: INFO
    instance class: INFO
